### ISSUE TITLE
[Feat] UT를 위한 찌르기 화면을 구현합니다.

### ISSUE THREAD

**Issue by bluehyudawn** [DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch#10]
### 📝 작업 목적

스프린트 기간 내 UT를 위한 테스트 화면을 구현합니다. 

---

### 🛠️ Tasks

- [x] 닉네임 입력(Text Field)
- [x] 찌르기 / 설정 선택(Button)
- [x] 유저 리스트(Navigation View + List)
