### ISSUE TITLE
[Feat] UT를 위한 '찌르기' 기능과 커스텀 로컬 푸시 알림을 구현합니다.

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch#16]
### 📝 작업 목적

- 만들어진 찌르기 테스트 뷰와 FCM 테스트 뷰를 합치고, 서버와 통신하는 로직을 추가합니다. 
- 커스텀 로컬 알림을 구현합니다.

---

### 🛠️ Tasks
- [x] ContentView 로그인, 비로그인 분기 처리
- [x] 찌르기 뷰에 NotificationTestingView의 로직 연결
   - 찌르기 빈도 제한 (1시간에 최대 4번) (보류)
   - [x] 알림 메세지에 찌르는 사람 명시 "xx님이.." (sendNotification 메서드에 파라미터 추가)
   - [x] 백그라운드에서 알림이 나타나지 않는 현상 해결 (Capabilities > Background Modes > background processing 체크)
   - [ ] 찌르기 알림 뱃지 활성화
   - [ ] 찌르기 버튼 이모지 다르게 할 수 있게끔 (+ 알람 메세지는 "유저네임+이모지")
- [x] 로컬 알림 구현
   - [x] 알림 설정 모달뷰에 로직 연결 + 알림 시간 정의 및 예약 발송
   - [ ] 종료 시간을 선택하면 앱이 터지는 문제 해결
   - [ ] 모달 뷰 이탈 후 되돌아갔을 때 이전 내역 반영
   - [ ] 로컬 알림 클릭 여부 + 클릭한 시간 인식하는 메서드 구현 
- [x] Firebase 서버 관련 작업
  - [x] Firebase 서버 구조 수정 (콜렉션명 변경, 필드 추가)
  - [x] 필요한 메서드 추가
  - [x] 찌르기 버튼에 Poke 생성 메서드 연결
  - [ ] fetchMembers 메서드 중복 패치 현상 해결 
- [ ] GA 이벤트 로그 삽입
