### ISSUE TITLE
[Refactor] LocalPushNotificationManger 로직을 리팩토링 하고 추가 작업을 진행합니다. 

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch#29]
### 📝 작업 목적

 - LocalPushNotificationManger 로직을 리팩토링하고, 로컬 푸시 알림이 화면이 띄워지지 않는 현상 등을 해결합니다

---

### 🛠️ Tasks

- [x] 설정된 조건대로 푸시 알림이 발송되는지 점검 및 로직 코드 리팩토링
- [x] notification permission request 시점 늦추는 조건 추가 (테스트 뷰에서 확인 완료)
- [x] Background task를 추가해 자정마다 앱이 백그라운드에서 자동 업데이트 되도록 설계 시도 (더이상 채택하지 않는 방법)
- [x] 뷰에서 시간 범위 제한하는 조건 및 문구 ("최대 15시간..") 추가 + UI 변경
- [x] 알림 인터벌 최소 단위 10분 -> 30분으로 변경
