### ISSUE TITLE
[Feat] Firebase 통신을 위한 모델과 뷰모델을 구현합니다.

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch#3]
### 📝 작업 목적

- Firebase 통신을 위한 Group, Member, Poke 구조체와 GroupViewModel, MemberViewModel, PokeViewModel을 구현합니다.

---

### 🛠️ Tasks
- [x] Group, Member 구조체 생성
- [x] GroupViewModel, MemberViewModel 생성
  - [x] CR 메서드 추가 (UD는 추후에)
